pretrained_model_name_or_path: "stabilityai/stable-video-diffusion-img2vid-xt-1-1"

# dataset
data_root: "/home/hj/data/YouTubeVOS/youtube-vos/JPEGImages/"
width: 320
height: 192
num_frames: 8      # ✅ 改成 8 的倍数

# training parameters
seed: 123
per_gpu_batch_size: 1
learning_rate: 0.00001

max_train_steps: 5000
validation_steps: 1000
mixed_precision: "fp16"

checkpointing_steps: 1000
checkpoints_total_limit: 1
output_dir: "./output"
